site_name: "SoC and Embedded Linux"

theme:
  name: active-handout-theme

docs_dir: docs-src
site_dir: docs
repo_name: "Insper/Embarcados-Avancados"
repo_url: "https://github.com/insper/Embarcados-Avancados"
edit_uri: "https://github.com/Insper/Embarcados-Avancados/edit/master/docs-src/"
site_url: "https://insper.github.io/Embarcados-Avancados/"
copyright: "Copyright &copy; 2019 / Prof. Rafael Corsi / rafael.corsi@insper.edu.br"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - termynal
  - active-handout:
      telemetry: true
      backend_url: http://localhost:8080/api/
      course_slug: Embedded-Linux-SoC
      plugin_exercise_counter: false

extra:
  custom_variables:
    entrega_1_deadline: 29/09/2023
    entrega_1_classroom: https://classroom.github.com/a/DHwwnXCQ
    entrega_1_forms: https://docs.google.com/forms/d/e/1FAIpQLSe3TKNxu2SV4Rm7QUyj3hq6Yt1YB5BWweT4zSXWMQHSDh6XpA/viewform?usp=sf_link

    entrega_2_deadline: TBD
    entrega_2_classroom: https://classroom.github.com/a/X1VhdjzW
    entrega_2_forms:  https://docs.google.com/forms/d/e/1FAIpQLSe3TKNxu2SV4Rm7QUyj3hq6Yt1YB5BWweT4zSXWMQHSDh6XpA/viewform?usp=sf_link

    entrega_3_deadline: TBD
    entrega_3_classroom: https://classroom.github.com/a/EVfsoSFX

    entrega_4_classroom: https://classroom.github.com/a/Qc6_OnhL

    entrega_forms:  https://docs.google.com/forms/d/e/1FAIpQLSe3TKNxu2SV4Rm7QUyj3hq6Yt1YB5BWweT4zSXWMQHSDh6XpA/viewform?usp=sf_link
    
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - FPGA:
      - 1.  FPGA RTL: "Tutorial-FPGA-RTL.md"
      - 🔔 Assigment: "Entrega-1.md"
      - 2.  FPGA NIOS: "Tutorial-FPGA-NIOS.md"
      - 🔔 Assigment: "Entrega-2.md"
      - 3.  FPGA NIOS IP: "Tutorial-FPGA-NIOS-IP.md"
      - 🔔 Assigment: "Entrega-3.md"
 
  - HPS:
      - 4. HPS: "Tutorial-HPS.md"
      - 5. HPS-Running: "Tutorial-HPS-Running.md"
      - 6. HPS-BuildSystem: "Tutorial-HPS-BuildSystem.md"
      - 7. HPS-BlinkLED: "Tutorial-HPS-BlinkLED.md"
      -  Extra - Network: "info-HPS-ethernet.md"
      - 🔔 Assigment: "Entrega-4.md"

      - 8. HPS-Kernel: "Tutorial-HPS-Kernel.md"
      - 9. HPS-Buildroot: "Tutorial-HPS-Buildroot.md"
      - 10. Extra - HPS-buildroot-scripts: "info-HPS-buildroot-scripts.md"
      - 🔔 Assigment: "Entrega-5.md"
      
      - 11. HPS-DeviceDriver: "Tutorial-HPS-DeviceDriver.md"
      - 12. HPS-Kernel-Module: "Tutorial-HPS-kernel-module.md"
      - 13. HPS-Kernel-Char_Device_Driver: "Tutorial-HPS-kernel-chardriver.md"
      
  - HPS + FPGA:
      - 14. HPS-FPGA-BlinkLED: "Tutorial-HPS-FPGA-BlinkLED.md"
      - 15. HPS-FPGA-VGA: "Tutorial-HPS-FPGA-VGA.md"
      - 🔔 Assigment:  "Entrega-6.md"
      - 16. HPS-FPGA-Kernel-Char_LED_Driver: "Tutorial-HPS-FPGA-kernel-char-led-driver.md"
      
  - High Level Synthesis:
      - 17.  Acelerando-HLS: "Tutorial-Acelerando-HLS.md"
      - 🔔 Assigment:"Entrega-Extra-1.md"

  - "Useful":
      - Softwares: "info-FPGA-e-Softwares.md"
      - SD card: "info-SDcard.md"
      - Serial port: "info-HPS-Serial.md"
      - Network: "info-HPS-ethernet.md"
      - Refereces: "info-VHDL.md"

  - "Students tutorials":
      - "Projeto-Overview.md"
      - "Projeto-Rubrica.md"
      - "Template markdown": "https://github.com/Insper/Embarcados-Avancados-Template"
      - 2022 - TFTP: 2022/tftp/index.md
      - 2022 - RISC V: 2022/riscv/index.md
      - 2022 - RaSpider: 2022/RaSpider/index.md
      - 2021 - Chisel: 2021/Chisel/index.md
      - 2021 - RISC V: 2021/RISCV/index.md
      - 2020 - PS3 HACK: "2020/PS3-Linux-Tutorial/index.md"
      - 2020 - Android para Raspbery Pi 3: "2020/Android/index.md"
      - 2020 - IP para fita de LED: "2020/LED-HW/index.md"
      - 2020 - Driver linux fita de LED: "2020/LED-Linux/index.md"
      - 2020 - Soc & Python: "2020/python/index.md"
      - 2020 - SDAccel: "2020/metropolis/index.md"
      - 2020 - Áudio na DE10: "2020/Audio/index.md"
      - 2020 - Criptografia em Hardware: "2020/cripto/index.md"
      - 2019 - TensorFlow: "2019/Gabriel-TensorFlow.md"
      - 2019 - OpenCL: "2019/Leo-OpenCL.md"
      - 2019 - Yocto: "2019/Elisa-Yocto.md"
      - 2019 - OpenCV: "2019/Pedro-OpenCV.md"
      - 2019 - FPGA na AWS: "2019/Martim-F1.md"
      - 2019 - DeviceDriver: "2019/Toranja-DevDriver.md"
