site_name: "SoC and Embedded Linux"

theme:
  name: active-handout-theme

docs_dir: docs-src
site_dir: docs
repo_name: "Insper/Embarcados-Avancados"
repo_url: "https://github.com/insper/Embarcados-Avancados"
edit_uri: "https://github.com/Insper/Embarcados-Avancados/edit/master/docs-src/"
site_url: "https://insper.github.io/Embarcados-Avancados/"
copyright: "Copyright &copy; 2019 / Prof. Rafael Corsi / rafael.corsi@insper.edu.br"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - termynal
  - active-handout:
      telemetry: true
      backend_url: http://localhost:8080/api/
      course_slug: Embedded-Linux-SoC
      plugin_exercise_counter: false

extra:
  custom_variables:
    entrega_1_deadline: 29/09/2023
    entrega_1_classroom: https://classroom.github.com/a/DHwwnXCQ
    entrega_1_forms: https://docs.google.com/forms/d/e/1FAIpQLSe3TKNxu2SV4Rm7QUyj3hq6Yt1YB5BWweT4zSXWMQHSDh6XpA/viewform?usp=sf_link

    entrega_2_deadline: TBD
    entrega_2_classroom: https://classroom.github.com/a/X1VhdjzW
    entrega_2_forms:  https://docs.google.com/forms/d/e/1FAIpQLSe3TKNxu2SV4Rm7QUyj3hq6Yt1YB5BWweT4zSXWMQHSDh6XpA/viewform?usp=sf_link


markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - HPS:
      - "Tutorial-HPS.md"
      - "Tutorial-HPS-Running.md"
      - "Tutorial-HPS-BuildSystem.md"
      - "Tutorial-HPS-BlinkLED.md"
      - "Extra: configurando rede": "info-HPS-ethernet.md"
      - Entrega 2: "Entrega-4.md"
      - "Tutorial-HPS-Kernel.md"
      - "Tutorial-HPS-Buildroot.md"
      - "info-HPS-buildroot-scripts.md"
      - Entrega 4: "Entrega-5.md"
      - "Tutorial-HPS-DeviceDriver1.md"
      - "Tutorial-HPS-kernel-module.md"
      - "Tutorial-HPS-kernel-chardriver.md"
  - "HPS + FPGA":
      - "Tutorial-HPS-FPGA-BlinkLED.md"
      - "Tutorial-HPS-FPGA-VGA.md"
      - Entrega 6: "Entrega-6.md"
      - "Tutorial-HPS-FPGA-kernel-char-led-driver.md"
  - "Acelerando":
      - "Tutorial-Acelerando-HLS.md"
      - "Entrega-Extra-1.md"
  - FPGA:
      - "Tutorial-FPGA-RTL.md"
      - Entrega 1: "Entrega-1.md"
      - "Tutorial-FPGA-NIOS.md"
      - Entrega 3: "Entrega-2.md"
      - Entrega 5: "Entrega-3.md"
      - "Tutorial-FPGA-NIOS-IP.md"
  - "Tutoriais Alunos":
      - "Projeto-Overview.md"
      - "Projeto-Rubrica.md"
      - "Template markdown": "https://github.com/Insper/Embarcados-Avancados-Template"
      - "2020/PS3-Linux-Tutorial/index.md"
      - "2020/Android/index.md"
      - "2020/LED-HW/index.md"
      - "2020/LED-Linux/index.md"
      - "2020/python/index.md"
      - "2020/metropolis/index.md"
      - "2020/Audio/index.md"
      - "2020/cripto/index.md"
      - "2019/Gabriel-TensorFlow.md"
      - "2019/Leo-OpenCL.md"
      - "2019/Elisa-Yocto.md"
      - "2019/Pedro-OpenCV.md"
      - "2019/Martim-F1.md"
      - "2019/Toranja-DevDriver.md"
  - "Úteis":
      - "info-FPGA-e-Softwares.md"
      - "info-VHDL.md"
      - "info-SDcard.md"
      - "info-HPS-Serial.md"
      - "info-HPS-ethernet.md"
      - "info-dtb.md"
