
site_name: 'Eletiva: Embarcados Avançados (SoC e Linux Embarcado)'

theme:
  features:
    - instant
    - navigation.expand
    - tabs: true
  name: 'material'
  palette:
      primary: 'white'
      accent: 'pink'
  font:
    text: Roboto
    code: Roboto Mono

# Copyright
copyright: 'Copyright &copy; 2019 / Prof. Rafael Corsi / rafael.corsi@insper.edu.br'

# repo
docs_dir: docs-src
site_dir: docs

repo_name: 'Insper/Embarcados-Avancados'
repo_url: 'https://github.com/insper/Embarcados-Avancados'
edit_uri: 'https://github.com/Insper/Embarcados-Avancados/edit/master/docs-src/'
site_url: 'https://insper.github.io/Embarcados-Avancados/'

nav:
  - Home: index.md
  - FPGA:
      - 'Tutorial-FPGA-RTL.md'
      - 'Entrega-1.md'
      - 'Tutorial-FPGA-NIOS.md'
      - 'Entrega-2.md'
      - 'Tutorial-FPGA-NIOS-IP.md'
      - 'Entrega-3.md'
  - HPS:
      - 'Tutorial-HPS.md'
      - 'Tutorial-HPS-Running.md'
      - 'Tutorial-HPS-BuildSystem.md'
      - 'Tutorial-HPS-BlinkLED.md'
      - 'Extra: configurando rede': 'info-HPS-ethernet.md'
      - 'Entrega-4.md'
      - 'Tutorial-HPS-Kernel.md'
      - 'Tutorial-HPS-Buildroot.md'
      - 'Entrega-5.md'
      - 'Tutorial-HPS-DeviceDriver1.md'
      - 'Tutorial-HPS-kernel-module.md'
      - 'Tutorial-HPS-kernel-chardriver.md'
        #      - 'Tutorial-HPS-kernel-chardriver-led.md'
  - 'HPS + FPGA':
      - 'Tutorial-HPS-FPGA-BlinkLED.md'
      - 'Tutorial-HPS-FPGA-kernel-char-led-driver.md'
  - 'Acelerando':
      - 'Tutorial-Acelerando-HLS.md'
  - 'Extras':
      - 'Tutorial-HPS-FPGA-VGA.md'
      - 'Entrega-6.md'
      - 'Entrega-Extra-1.md'
  - 'Úteis':
      - 'info-FPGA-e-Softwares.md'
      - 'info-VHDL.md'
      - 'info-SDcard.md'
      - 'info-HPS-Serial.md'
      - 'info-HPS-ethernet.md'
  - 'Tutoriais Alunos':
      - 'Projeto-Overview.md'
      - 'Projeto-Rubrica.md'
      - 'Template markdown': 'https://github.com/Insper/Embarcados-Avancados-Template' 
      - 2020:
          - '2020/Temas.md'
          - '2020/PS3-Linux-Tutorial/index.md'
      - 2019:
          - '2019/Tutoriais.md'
          - '2019/Gabriel-TensorFlow.md'
          - '2019/Leo-OpenCL.md'
          - '2019/Elisa-Yocto.md'
          - '2019/Pedro-OpenCV.md'
          - '2019/Martim-F1.md'
          - '2019/Toranja-DevDriver.md'

# extras
extra_css:
  - css/progress.css
 
extra_javascript:
  - 'js/dom-confetti.js'
  - 'js/progress.js'

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
