extensions:
  - notification
  - translate-admonitions
  - quiz
  - short-questions
  - progress-check
  - slides
  - counter
  - notifi-outdate-page

config:
  short-questions:
    text: "Check"
  counter:
    - question
    - tip
  notifi-outdate-page:
    text: "Please refresh this page, the content has been updated 🗘."
